# Social Vulnerability Logroño - Census Data

## Environment

### R Libraries
Any required R libraries are imported into the kernal:

In [1]:
# Load R libraries
## none required

### Output directory

In [2]:
# create the pipeline directory if it does not exist
pipeline_dir <- file.path("../..","2_pipeline","Spain","Logrono","1a_CensusData","2021")
if(!dir.exists(pipeline_dir)){
    dir.create(pipeline_dir, recursive = TRUE)
    print(paste0(pipeline_dir, " created"))
}

## Load Data

### Import the csv data

In [3]:
# Read the census data
# Current Spanish 2021 Census is a mixture of:
#  1) a static CSV or Excel downloaded from the INE Census website
#  2) extra data from missing indicators appended into this CSV or Excel
# in our case we read the CSV version
census_data <- read.csv("../../0_data/census/Spain/2021/Census_Data_2024-07-03_Census.csv", sep=",")
head(census_data)

census_homes_year_of_construction_data <- read.csv("../../0_data/census/Spain/2021/Censo_2021_custom_query__Family_homes__Year_of_construction__17_La_Rioja.csv", sep=",")
head(census_homes_year_of_construction_data)

census_household_structure_data <- read.csv("../../0_data/census/Spain/2021/Censo_2021_custom_query__People_living_in_family_homes__Household_structure__17_La_Rioja.csv", sep=",")
head(census_household_structure_data)

  ccaa CPRO CMUN dist secc t1_1 t2_1 t2_2 t3_1  t4_1 ⋯ t22_3 t22_4 t22_5
1 17   26   1    1    1     236 0.41 0.59 50.97 0.10 ⋯  18    13    4
2 17   26   2    1    1    1150 0.45 0.55 45.56 0.12 ⋯  88    71   27
3 17   26   3    1    1     460 0.48 0.52 52.59 0.10 ⋯  27    31    6
4 17   26   4    1    1      67   NA   NA    NA   NA ⋯  NA    NA   NA
5 17   26   5    1    1    1828 0.48 0.52 46.31 0.13 ⋯ 114    95   61
6 17   26   5    2    1    1682 0.49 0.51 39.04 0.21 ⋯ 136   128   42
  c_ab0t4 c_ag0t4 c_amo75 c_afo75 c_ac5t9 fam_3plus fam_bb_1970
1  3       3       20      18      10     NA        NA
2 20      20       62      78      45     NA        NA
3  2       6       36      52      19     NA        NA
4  1       0        6       2       0     NA        NA
5 25      29      104     151      67     NA        NA
6 64      48       60      87     105     NA        NA

  home_year_id home_total before_1900 from_1900_to_1920 from_1921_to_1940
1 2600201001    975       81          27                 45
2 2600301001    768       21          90                171
3 2600501001   1581       48          81                 57
4 2600502001   1011        9           6                  9
5 2600601001   1854       36          54                 42
6 2600701001    681        0          54                 99
  from_1941_to_1950 from_1951_to_1960 from_1961_a_1970 from_1971_to_1980
1  54                33                33              102
2 120                63                90               54
3  27                48                57              156
4  24                33                42               39
5  57                72               123              189
6 111               111                51               75
  from_1981to_1990 from_1991_to_2000 from_2001_to_2010 from_2011_to_2020
1  69              129               342               39
2  45               21                36               18
3 147              129                57               36
4  57              111               579               30
5 246              195               525               51
6  51               33                51                3
  not_recorded
1  18
2  39
3 735
4  78
5 264
6  39

  household_structure_id household_structure_total single_female_under_65
1 2600201001             1149                      33
2 2600501001             1686                      33
3 2600502001             1683                      60
4 2600601001             2511                      66
5 2600701001              642                      15
6 2600801001             1374                       9
  single_male_under_65 single_female_over_65 single_male_over_65
1  72                  42                    36
2  90                  51                    48
3  87                  27                    24
4 120                  78                    48
5  42                  45                    24
6  39                  48                    27
  single_parent_with_a_child_under_25 single_parent_with_all_children_over_25
1  60                                 39
2  78                                 57
3 147                                 30
4 192                                 78
5  24                                 48
6  51                                 66
  couple_without_children couple_with_a_child_under_25
1 162                     333
2 267                     516
3 210                     651
4 402                     891
5  99                     171
6 189                     558
  couple_with_all_children_over_25
1  78
2  99
3  99
4 183
5  51
6 132
  couple_or_single_parent_with_a_child_under_25_years_and_more_person
1 144
2 261
3 174
4 282
5  78
6 168
  other_household
1 150
2 189
3 174
4 174
5  45
6  93

## Prepare data
We only require a subset of the census data for our purposes. We therefore need to extract the relevant data, then combine these to create our vulnerability indicators.

In addition, the raw data is not suitable for use within the vulnerabiltiy assessment. It needs to be normalised based on the number of people/households within each small area. Therefore, the data is converted to percentages based on the total persons/households within each small area.

### Supporting data

#### Code that uniquely identifies the census area

In [4]:
identifier <- c('ccaa', 'CPRO', 'CMUN', 'dist', 'secc')
census_area_id <- census_data[, identifier, drop = FALSE]

### Merge Census datasets

In [5]:
# number of rows in the census data - base
head( nrow(census_data) )

# number of rows in the census data - family homes: year of construction
#                                   - family homes: household structure
# Note: information from some census sections has been suppressed to protect statistical confidentiality
head( nrow(census_homes_year_of_construction_data) )
head( nrow(census_household_structure_data) )

# construct the identifier - family homes: year of construction
census_homes_year_of_construction_data$ccaa = as.integer(17)
census_homes_year_of_construction_data$CPRO = as.integer(substr(census_homes_year_of_construction_data$home_year_id, 1, 2))
census_homes_year_of_construction_data$CMUN = as.integer(substr(census_homes_year_of_construction_data$home_year_id, 3, 5))
census_homes_year_of_construction_data$dist = as.integer(substr(census_homes_year_of_construction_data$home_year_id, 6, 7))
census_homes_year_of_construction_data$secc = as.integer(substr(census_homes_year_of_construction_data$home_year_id, 8, 10))

# construct the identifier - family homes: household structure
census_household_structure_data$ccaa = as.integer(17)
census_household_structure_data$CPRO = as.integer(substr(census_household_structure_data$household_structure_id, 1, 2))
census_household_structure_data$CMUN = as.integer(substr(census_household_structure_data$household_structure_id, 3, 5))
census_household_structure_data$dist = as.integer(substr(census_household_structure_data$household_structure_id, 6, 7))
census_household_structure_data$secc = as.integer(substr(census_household_structure_data$household_structure_id, 8, 10))

# merge using the identifier
census_data <- merge(census_data, census_homes_year_of_construction_data, by=identifier, all.x=TRUE)
census_data <- merge(census_data, census_household_structure_data, by=identifier, all.x=TRUE)

head(census_data)

[1] 343

[1] 202

[1] 209

  ccaa CPRO CMUN dist secc t1_1 t2_1 t2_2 t3_1  t4_1 ⋯ single_male_under_65
1 17   26   1    1    1     236 0.41 0.59 50.97 0.10 ⋯ NA
2 17   26   2    1    1    1150 0.45 0.55 45.56 0.12 ⋯ 72
3 17   26   3    1    1     460 0.48 0.52 52.59 0.10 ⋯ NA
4 17   26   4    1    1      67   NA   NA    NA   NA ⋯ NA
5 17   26   5    1    1    1828 0.48 0.52 46.31 0.13 ⋯ 90
6 17   26   5    2    1    1682 0.49 0.51 39.04 0.21 ⋯ 87
  single_female_over_65 single_male_over_65 single_parent_with_a_child_under_25
1 NA                    NA                   NA
2 42                    36                   60
3 NA                    NA                   NA
4 NA                    NA                   NA
5 51                    48                   78
6 27                    24                  147
  single_parent_with_all_children_over_25 couple_without_children
1 NA                                       NA
2 39                                      162
3 NA                                       NA
4 NA                                       NA
5 57                                      267
6 30                                      210
  couple_with_a_child_under_25 couple_with_all_children_over_25
1  NA                          NA
2 333                          78
3  NA                          NA
4  NA                          NA
5 516                          99
6 651                          99
  couple_or_single_parent_with_a_child_under_25_years_and_more_person
1  NA
2 144
3  NA
4  NA
5 261
6 174
  other_household
1  NA
2 150
3  NA
4  NA
5 189
6 174

### Totals

#### Population total

In [6]:
population_total <- census_data[, 't1_1', drop = FALSE]
names(population_total)[1] <- 'population_total'
head(population_total)

  population_total
1  236
2 1150
3  460
4   67
5 1828
6 1682

#### Dwellings total

In [7]:
dwellings_total <- census_data[, 't18_1', drop = FALSE]
names(dwellings_total)[1] <- 'dwellings_total'
head(dwellings_total)

  dwellings_total
1  284
2  976
3  768
4   NA
5 1581
6 1010

#### Households total

In [8]:
households_total <- census_data[, 't21_1', drop = FALSE]
names(households_total)[1] <- 'households_total'
head(households_total)

  households_total
1 112
2 495
3 215
4  NA
5 697
6 673

### Domain data

#### Age domain

In [9]:
### Domain:Age ###

# Age - early childhood boy (under 5 years old)
early_childhood_boy_fields <- c(
    'c_ab0t4' # Age 0 to 4 boys
)
early_childhood_boy_data <- census_data[, early_childhood_boy_fields, drop = FALSE]
early_childhood_boy <- rowSums(early_childhood_boy_data, na.rm=TRUE)
early_childhood_boy_pct <- (early_childhood_boy / population_total) * 100.0
names(early_childhood_boy_pct)[1] <- 'early_childhood_boy_pct'

# Age - early childhood girl (under 5 years old)
early_childhood_girl_fields <- c(
    'c_ag0t4' # Age 0 to 4 girls
)
early_childhood_girl_data <- census_data[, early_childhood_girl_fields, drop = FALSE]
early_childhood_girl <- rowSums(early_childhood_girl_data, na.rm=TRUE)
early_childhood_girl_pct <- (early_childhood_girl / population_total) * 100.0
names(early_childhood_girl_pct)[1] <- 'early_childhood_girl_pct'

# Age - middle to oldest old male (75+ years old)
age_middle_to_oldest_old_male_fields <- c(
    'c_amo75' # Age 75+ males
)
age_middle_to_oldest_old_male_data <- census_data[, age_middle_to_oldest_old_male_fields, drop = FALSE]
age_middle_to_oldest_old_male <- rowSums(age_middle_to_oldest_old_male_data, na.rm=TRUE)
age_middle_to_oldest_old_male_pct <- (age_middle_to_oldest_old_male / population_total) * 100.0
names(age_middle_to_oldest_old_male_pct)[1] <- 'age_middle_to_oldest_old_male_pct'

# Age - middle to oldest old male (75+ years old)
age_middle_to_oldest_old_female_fields <- c(
    'c_afo75' # Age 75+ females
)
age_middle_to_oldest_old_female_data <- census_data[, age_middle_to_oldest_old_female_fields, drop = FALSE]
age_middle_to_oldest_old_female <- rowSums(age_middle_to_oldest_old_female_data, na.rm=TRUE)
age_middle_to_oldest_old_female_pct <- (age_middle_to_oldest_old_female / population_total) * 100.0
names(age_middle_to_oldest_old_female_pct)[1] <- 'age_middle_to_oldest_old_female_pct'

# Combine all these indicators into an array for this domain
age_domain_pct <- cbind(early_childhood_boy_pct,
                        early_childhood_girl_pct,
                        age_middle_to_oldest_old_male_pct,
                        age_middle_to_oldest_old_female_pct)

# Print the first six rows of the data to visually check it looks OK
head(age_domain_pct)

  early_childhood_boy_pct early_childhood_girl_pct
1 1.2711864               1.271186
2 1.7391304               1.739130
3 0.4347826               1.304348
4 1.4925373               0.000000
5 1.3676149               1.586433
6 3.8049941               2.853746
  age_middle_to_oldest_old_male_pct age_middle_to_oldest_old_female_pct
1 8.474576                           7.627119
2 5.391304                           6.782609
3 7.826087                          11.304348
4 8.955224                           2.985075
5 5.689278                           8.260394
6 3.567182                           5.172414

#### Health domain

In [10]:
### Domain:Health ###

# Health - people with a disability preventing work (already a percentage)
disability_fields <- c(
    't13_1'
)
disability_data <- census_data[, disability_fields, drop = FALSE]
disability <- rowSums(disability_data, na.rm=TRUE)
disability_pct <- disability

# Combine all these indicators into an array for this domain
health_domain_pct <- cbind(disability_pct)

# Print the first six rows of the data to visually check it looks OK
head(health_domain_pct)

     disability_pct
[1,] 0.03
[2,] 0.02
[3,] 0.01
[4,] 0.00
[5,] 0.03
[6,] 0.02

#### Income domain

In [11]:
### Domain:Income ###

# One parent households
one_parent_households_fields <- c(
    'single_parent_with_a_child_under_25'
)
one_parent_households_data <- census_data[, one_parent_households_fields, drop = FALSE]
one_parent_households <- rowSums(one_parent_households_data, na.rm=TRUE)
one_parent_households_pct <- (one_parent_households / households_total) * 100.0
names(one_parent_households_pct)[1] <- 'one_parent_households_pct'

# Dependants under 16 years of age (already a percentage)
dependants_fields <- c(
    't4_1'
)
dependants_data <- census_data[, dependants_fields, drop = FALSE]
dependants <- rowSums(dependants_data, na.rm=TRUE)
dependants_pct <- dependants

# Unemployment (already a percentage)
unemployment_fields <- c(
    't10_1'
)
unemployment_data <- census_data[, unemployment_fields, drop = FALSE]
unemployment <- rowSums(unemployment_data, na.rm=TRUE)
unemployment_pct <- unemployment

# population attending university (already a percentage)
attending_university_fields <- c(
    't8_1'
)
attending_university_data <- census_data[, attending_university_fields, drop = FALSE]
attending_university <- rowSums(attending_university_data, na.rm=TRUE)
attending_university_pct <- attending_university

# Combine all these indicators into an array for this domain
income_domain_pct <- cbind(one_parent_households_pct,
                           dependants_pct,
                           unemployment_pct,
                           attending_university_pct)

# Print the first six rows of the data to visually check it looks OK
head(income_domain_pct)

  one_parent_households_pct dependants_pct unemployment_pct
1  0.00000                  0.10           0.04
2 12.12121                  0.12           0.16
3  0.00000                  0.10           0.08
4       NA                  0.00           0.00
5 11.19082                  0.13           0.18
6 21.84250                  0.21           0.10
  attending_university_pct
1 0.05
2 0.03
3 0.04
4 0.00
5 0.02
6 0.03

#### Information Access/Use domain

In [12]:
### Domain:Information Access/Use ###

# No higher education (already a percentage)
no_higher_education_fields <- c(
    't9_1' # need to invert
)
no_higher_education_data <- census_data[, no_higher_education_fields, drop = FALSE]
no_higher_education <- rowSums(no_higher_education_data, na.rm=TRUE)
no_higher_education_pct <- (1.0-no_higher_education) # invert

# Combine all these indicators into an array for this domain
info_domain_pct <- cbind(no_higher_education_pct)

# Print the first six rows of the data to visually check it looks OK
head(info_domain_pct)

     no_higher_education_pct
[1,] 0.77
[2,] 0.80
[3,] 0.79
[4,] 1.00
[5,] 0.80
[6,] 0.75

#### Local knowledge domain

In [13]:
### Domain:Local Knowledge ###

# Foreign nationals (already a percentage)
foreign_nationals_fields <- c(
    't5_1'
)
foreign_nationals_data <- census_data[, foreign_nationals_fields, drop = FALSE]
foreign_nationals <- rowSums(foreign_nationals_data, na.rm=TRUE)
foreign_nationals_pct <- foreign_nationals

# Combine all these indicators into an array for this domain
local_knowledge_domain_pct <- cbind(foreign_nationals_pct)

# Print the first six rows of the data to visually check it looks OK
head(local_knowledge_domain_pct)

     foreign_nationals_pct
[1,] 0.11
[2,] 0.16
[3,] 0.13
[4,] 0.00
[5,] 0.15
[6,] 0.11

#### Physical access domain

In [14]:
###  Domain:Tenure ###

# Households renting
rented_fields <- c(
    't20_2'
)
rented_data <- census_data[, rented_fields, drop = FALSE]
rented <- rowSums(rented_data, na.rm=TRUE)
rented_pct <- (rented / dwellings_total) * 100.0
names(rented_pct)[1] <- 'rented_pct'

# Combine all these indicators into an array for this domain
tenure_domain_pct <- cbind(rented_pct)

# Print the first six rows of the data to visually check it looks OK
head(tenure_domain_pct)

  rented_pct
1 4.577465
2 4.610656
3 1.822917
4       NA
5 4.111322
6 5.247525

#### Social Network domain data

In [15]:
### Domain:Social Network ###

# Primary school age children
primary_school_age_fields <- c(
    'c_ac5t9'
)
primary_school_age_data <- census_data[, primary_school_age_fields, drop = FALSE]
primary_school_age <- rowSums(primary_school_age_data, na.rm=TRUE)
primary_school_age_pct <- (primary_school_age / population_total) * 100.0
names(primary_school_age_pct)[1] <- 'primary_school_age_pct'

# One person households
one_person_households_fields<- c(
    't22_1'
)
one_person_households_data <- census_data[, one_person_households_fields, drop = FALSE]
one_person_households <- rowSums(one_person_households_data, na.rm=TRUE)
one_person_households_pct <- (one_person_households / households_total) * 100.0
names(one_person_households_pct)[1] <- 'one_person_households_pct'

# Combine all these indicators into an array for this domain
social_network_domain_pct <- cbind(primary_school_age_pct,
                                   one_person_households_pct)

# Print the first six rows of the data to visually check it looks OK
head(social_network_domain_pct)

  primary_school_age_pct one_person_households_pct
1 4.237288               41.07143
2 3.913043               36.76768
3 4.130435               38.60465
4 0.000000                     NA
5 3.665208               31.99426
6 6.242568               29.12333

#### Housing Characteristics domain

In [16]:
### Domain: Housing Characteristics ####

# Indicator: Persons residing in family homes - year built pre 1970
#    'fam_bb_1970'
year_built_fields <- c(
    'before_1900',
    'from_1900_to_1920',
    'from_1921_to_1940',
    'from_1941_to_1950',
    'from_1951_to_1960',
    'from_1961_a_1970'
)
year_built_data <- census_data[, year_built_fields, drop = FALSE]
year_built <- rowSums(year_built_data, na.rm=TRUE)
year_built_pct <- (year_built / dwellings_total) * 100.0
names(year_built_pct)[1] <- 'year_built_pct'
#year_built_pct[is.na(year_built_pct)] <- 0

# Combine all these indicators into an array for this domain
housing_characteristics_domain_pct <- cbind(year_built_pct)

# Print the first six rows of the data to visually check it looks OK
head(housing_characteristics_domain_pct)

  year_built_pct
1  0.00000
2 27.97131
3 72.26562
4       NA
5 20.11385
6 12.17822

### Combine all data into one table

In [17]:
# Combine all data into one table
indicator_domains_pct <- cbind(census_area_id,
                               age_domain_pct,
                               health_domain_pct,
                               income_domain_pct,
                               info_domain_pct,
                               local_knowledge_domain_pct,
                               tenure_domain_pct,
                               social_network_domain_pct,
                               housing_characteristics_domain_pct)
head(indicator_domains_pct)

  ccaa CPRO CMUN dist secc early_childhood_boy_pct early_childhood_girl_pct
1 17   26   1    1    1    1.2711864               1.271186
2 17   26   2    1    1    1.7391304               1.739130
3 17   26   3    1    1    0.4347826               1.304348
4 17   26   4    1    1    1.4925373               0.000000
5 17   26   5    1    1    1.3676149               1.586433
6 17   26   5    2    1    3.8049941               2.853746
  age_middle_to_oldest_old_male_pct age_middle_to_oldest_old_female_pct
1 8.474576                           7.627119
2 5.391304                           6.782609
3 7.826087                          11.304348
4 8.955224                           2.985075
5 5.689278                           8.260394
6 3.567182                           5.172414
  disability_pct one_parent_households_pct dependants_pct unemployment_pct
1 0.03            0.00000                  0.10           0.04
2 0.02           12.12121                  0.12           0.16
3 0.01            0.00000                  0.10           0.08
4 0.00                 NA                  0.00           0.00
5 0.03           11.19082                  0.13           0.18
6 0.02           21.84250                  0.21           0.10
  attending_university_pct no_higher_education_pct foreign_nationals_pct
1 0.05                     0.77                    0.11
2 0.03                     0.80                    0.16
3 0.04                     0.79                    0.13
4 0.00                     1.00                    0.00
5 0.02                     0.80                    0.15
6 0.03                     0.75                    0.11
  rented_pct primary_school_age_pct one_person_households_pct year_built_pct
1 4.577465   4.237288               41.07143                   0.00000
2 4.610656   3.913043               36.76768                  27.97131
3 1.822917   4.130435               38.60465                  72.26562
4       NA   0.000000                     NA                        NA
5 4.111322   3.665208               31.99426                  20.11385
6 5.247525   6.242568               29.12333                  12.17822

## Calculate Z-Score
The raw data is not suitable for use within the vulnerabiltiy assessment. It needs to be standardised. Therefore, the data is converted to z-scores. Z-scores are:

>"A statistical measurement of a score's relationship to the mean (average value) in a group of scores. A Z-score of 0 means the score is the same as the mean (average value). A Z-score can be positive or negative, indicating whether it is above or below the mean and by how many standard deviations. Z-score standardisation represents the deviation of a raw score from its mean in standard deviation units." (Kazmierczak et al., 2015)

### Calculate the Z-score

In [18]:
# Copy the data
indicator_z_scores <- indicator_domains_pct

# Get the number of columns in the data
num_cols = ncol(indicator_z_scores)

# Calculate the z scores for each of the relevant columns - starting at the 2nd column
for(col in names(indicator_z_scores)[6:num_cols]) {
  # rename column (remove the '_pct' in the name)
  new_col_name <- gsub("_pct", "", col)
  indicator_z_scores[new_col_name] = scale(indicator_z_scores[col])
}

# Remove the original data to leave only the area identifier and the z scores
indicator_z_scores <- indicator_z_scores[-c(6:num_cols)]

head(indicator_z_scores)

  ccaa CPRO CMUN dist secc early_childhood_boy early_childhood_girl
1 17   26   1    1    1    -0.19258164         -0.1467916
2 17   26   2    1    1     0.23745377          0.3146154
3 17   26   3    1    1    -0.96122760         -0.1140934
4 17   26   4    1    1     0.01083739         -1.4002199
5 17   26   5    1    1    -0.10396496          0.1640514
6 17   26   5    2    1     2.13595981          1.4136596
  age_middle_to_oldest_old_male age_middle_to_oldest_old_female disability
1  0.4818082                    -0.10021618                      1.2753218
2 -0.2611307                    -0.31519260                      0.3880289
3  0.3255496                     0.83585043                     -0.4992639
4  0.5976241                    -1.28188374                     -1.3865567
5 -0.1893316                     0.06098884                      1.2753218
6 -0.7006675                    -0.72507994                      0.3880289
  one_parent_households dependants unemployment attending_university
1 -1.459709836          -0.0938240 -1.00214549   1.2303104
2 -0.007254482           0.1987363  0.87022439   0.2231589
3 -1.459709836          -0.0938240 -0.37802220   0.7267347
4           NA          -1.5566254 -1.62626879  -1.2875683
5 -0.118741371           0.3450164  1.18228604  -0.2804168
6  1.157623344           1.5152575 -0.06596055   0.2231589
  no_higher_education foreign_nationals rented     primary_school_age
1  0.07143877          0.1446865        -0.5073936  0.30936208
2  0.27339067          0.7793089        -0.5005024  0.16550926
3  0.20607337          0.3985355        -1.0793008  0.26195604
4  1.61973671         -1.2514828                NA -1.57053273
5  0.27339067          0.6523844        -0.6041755  0.05555571
6 -0.06319583          0.1446865        -0.3682738  1.19901504
  one_person_households year_built
1  1.0319635            -0.94812767
2  0.4903007             0.24638629
3  0.7214991             2.13797352
4         NA                     NA
5 -0.1104731            -0.08916627
6 -0.4718037            -0.42805727

### Output the Z-score data

In [19]:
# Output the z-score data as a csv file
output_file <- file.path(pipeline_dir, "censusDataZ.csv")
write.csv(indicator_z_scores, output_file, row.names = FALSE)

**END**